
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_boolean:
  woshi_fan_state:
    name: 风扇开关
    icon: mdi:fan
input_number:
  woshi_fan_speed:
    name: 风扇速度
    min: 0
    max: 100
    icon: mdi:fan-speed-1
  woshi_fan_direction:
    name: 风扇方向
    options:
      - 静音
      - 正常
    icon: mdi:fan-off


climate: !include climate.yaml
fan:
  - platform: template
    # https://www.home-assistant.io/integrations/fan.template
    fans: !include fan_woshi.yaml
switch:
  - platform: template
    switches: !include switch_kongtiao.yaml
